//Standard includes
#include <stdbool.h>
#include <stdint.h>

//Project includes
#include "pinout.h"
#include "EIB/Encoders.h"
#include "MotorDriver/MotorDriver.h"
#include "ControlLoop/ControlLoop.h"
#include "EIB/Encoders.h"

//Tivaware includes
#include "inc/hw_memmap.h"
#include "driverlib/gpio.h"
#include "driverlib/rom.h"
#include "driverlib/sysctl.h"
#include "driverlib/pin_map.h"
#include "driverlib/pwm.h"
#include "driverlib/adc.h"
#include "driverlib/ssi.h"
#include "driverlib/uart.h"
#include "utils/uartstdio.h"
#include "driverlib/uart.h"

//Testing
#include <math.h>
float angle = 0;

void EnableClock(void);
void EnablePeripherals(void);
void InitConsole(void);

static PositionVector vec;

int main(void)
{
    EnableClock();
    EnablePeripherals();

    //Disable broken joints
    MD_EnableMotor(JOINT4, false);
    //MD_EnableMotor(JOINT5, false); //Pending issue where encoder ticks are being missed when joint is rotating too fast.
    MD_EnableMotor(JOINT6, false);

    vec.x = 10;
    vec.y = 0;
    vec.z = 5;
    vec.theta = -90;

    float centerx = 10;
    float centery = 0;
    float radius = 2;

    while(1){
        float x = radius*cos(angle) + centerx;
        float y = radius*sin(angle) + centery;
        vec.x = x;
        vec.y = y;
        vec.theta = -90;
        SetArmPosition(vec);
        angle += M_PI * .002;
        SysCtlDelay(120000000 / 300);
    }
}

void EnableInvert(void);

void EnableClock(void){
    //Run the PLL at 120MHz
    SysCtlClockFreqSet((SYSCTL_XTAL_25MHZ |
                      SYSCTL_OSC_MAIN |
                      SYSCTL_USE_PLL |
                      SYSCTL_CFG_VCO_480), 120000000);
}

/*
    Enables all peripherals needed for this motor driver test
*/
void EnablePeripherals(void){
    //Use the pinout code generated by TI PinMux.

    //Enable the SPI Peripheral and wait for the clock to settle
    SysCtlPeripheralEnable(SYSCTL_PERIPH_SSI3);

    InitConsole();
    PinoutSet();
    InitializeControlLoop();
}

//Initializes UART0 to be used as a console.
void InitConsole(void){
    //
    // Enable GPIO port A which is used for UART0 pins.
    // TODO: change this to whichever GPIO port you are using.
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_GPIOA);

    //
    // Configure the pin muxing for UART0 functions on port A0 and A1.
    // This step is not necessary if your part does not support pin muxing.
    // TODO: change this to select the port/pin you are using.
    //
    GPIOPinConfigure(GPIO_PA0_U0RX);
    GPIOPinConfigure(GPIO_PA1_U0TX);

    //
    // Enable UART0 so that we can configure the clock.
    //
    SysCtlPeripheralEnable(SYSCTL_PERIPH_UART0);

    //
    // Use the internal 16MHz oscillator as the UART clock source.
    //
    UARTClockSourceSet(UART0_BASE, UART_CLOCK_PIOSC);

    //
    // Select the alternate (UART) function for these pins.
    // TODO: change this to select the port/pin you are using.
    //
    GPIOPinTypeUART(GPIO_PORTA_BASE, GPIO_PIN_0 | GPIO_PIN_1);

    //
    // Initialize the UART for console I/O.
    //
    UARTStdioConfig(0, 115200, 16000000);
}
